clc; clf; clear;

% Define base frequency
f = 130; 
d = 0.4; d4 = 4*d; 

% Define musical notes
[S,fs] = contour(2,0,d,f);
[S4,fs4] = contour(2,0,d4,f);
[R,fr] = contour(2,2,d,f);
[G,fg] = contour(2,4,d,f);
[M,fm] = contour(2,5,d,f);
[P,fp] = contour(2,7,d,f);
[p,fp] = contour(1,7,d,f);
[D,fd] = contour(2,9,d,f);
[m,fm] = contour(1,5,d,f);
[d,fd] = contour(1,9,d,f);
[N,fn] = contour(2,11,d,f);
[n,fn] = contour(1,11,d,f);
[St,fst] = contour(3,0,d,f);
[St4,fst4] = contour(3,0,d4,f);

% Doraemon Theme Tune Notes
x = [p S S G D G P ...
     P D P G m G R ...
     d R R m N N D P ...
     m m m n d n S R ...
     p S S G D G P ...
     P P D P G m G R ...
     d R R m N N D P ...
     m m m n d n S R ...
     D D D P m P D P ...
     R G m R P ...
     D P m ...
     R N D P D P m ...
     P D G R S];

% Corresponding Frequencies
f2 = [fp fs fs fg fd fg fp ...
      fp fd fp fg fm fg fr ...
      fd fr fr fm fn fn fd fp ...
      fm fm fm fn fd fn fs fr ...
      fp fs fs fg fd fg fp ...
      fp fp fd fp fg fm fg fr ...
      fd fr fr fm fn fn fd fp ...
      fm fm fm fn fd fn fs fr ...
      fd fd fd fp fm fp fd fp ...
      fr fg fm fr fp ...
      fd fp fm ...
      fr fn fd fp fd fp fm ...
      fp fd fg fr fs];

% Play sound
sound(x,22050);

% Plot stem diagram
stem(f2,'red','LineWidth',2);